baseURL = "https://gohugo.io"
title = "Hugo Themes"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
themesDir = "../../"

[params]
author = "Jacob Hilker"
description = "This is a website."
profilePic = "https://images.unsplash.com/photo-1630957437294-36e27ba9db1c"


[[params.socials]]
icon = "fab fa-gitlab"
url = "#"
name = "Gitlab"

[[params.socials]]
icon = "fab fa-github"
url = "#"
name = "Github"

[[params.socials]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "#"

[[params.socials]]
icon = "fab fa-dev"
title = "Dev.to"
url = "#"

[[params.socials]]
icon = "fab fa-codepen"
title = "CodePen"
url = "#"

[[params.socials]]
icon = "fas fa-envelope"
title = "Contact"
url = "#"


[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  
  [[menu.main]]
    identifier = "post"
    name = "Posts"
    url = "/post/"
    weight = 20


    

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
